### ISSUE TITLE
Range Single : If Size Chart is empty on the backend, the "view the size chart" link will open on a wrong page. We suggest to add an error message if no downloadable file is set.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/Sworn-to-the-Tribe#65]
![65](https://cloud.githubusercontent.com/assets/18256652/15848099/591669d2-2cbd-11e6-816e-6a105ecae925.png)

**Comment by judetitan** [comment]
Fixed if there is no uploaded file the link will not show
